// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: extension_repo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Niratan.Models.Manga.Protos {

  /// <summary>Holder for reflection information generated from extension_repo.proto</summary>
  public static partial class ExtensionRepoReflection {

    #region Descriptor
    /// <summary>File descriptor for extension_repo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExtensionRepoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRleHRlbnNpb25fcmVwby5wcm90bxITbmlyYXRhbi5tYW5nYS5taWhvbiLW",
            "AQoVTmV0d29ya0V4dGVuc2lvblN0b3JlEgwKBG5hbWUYASABKAkSEwoLYmFk",
            "Z2VfbGFiZWwYAiABKAkSEwoLc2lnbmluZ19rZXkYAyABKAkSLQoHY29udGFj",
            "dBgEIAEoCzIcLm5pcmF0YW4ubWFuZ2EubWlob24uQ29udGFjdBI6Cg5leHRl",
            "bnNpb25fbGlzdBhlIAEoCzIiLm5pcmF0YW4ubWFuZ2EubWlob24uRXh0ZW5z",
            "aW9uTGlzdBIaChJleHRlbnNpb25fbGlzdF91cmwYZiABKAkiKwoHQ29udGFj",
            "dBIPCgd3ZWJzaXRlGAEgASgJEg8KB2Rpc2NvcmQYAiABKAkiQwoNRXh0ZW5z",
            "aW9uTGlzdBIyCgpleHRlbnNpb25zGAEgAygLMh4ubmlyYXRhbi5tYW5nYS5t",
            "aWhvbi5FeHRlbnNpb24ikQIKCUV4dGVuc2lvbhIMCgRuYW1lGAEgASgJEhQK",
            "DHBhY2thZ2VfbmFtZRgCIAEoCRIxCglyZXNvdXJjZXMYAyABKAsyHi5uaXJh",
            "dGFuLm1hbmdhLm1paG9uLlJlc291cmNlcxIVCg1leHRlbnNpb25fbGliGAQg",
            "ASgJEhQKDHZlcnNpb25fY29kZRgFIAEoAxIUCgx2ZXJzaW9uX25hbWUYBiAB",
            "KAkSPAoPY29udGVudF93YXJuaW5nGAcgASgOMiMubmlyYXRhbi5tYW5nYS5t",
            "aWhvbi5Db250ZW50V2FybmluZxIsCgdzb3VyY2VzGAggAygLMhsubmlyYXRh",
            "bi5tYW5nYS5taWhvbi5Tb3VyY2UiLgoJUmVzb3VyY2VzEg8KB2Fwa191cmwY",
            "ASABKAkSEAoIaWNvbl91cmwYAiABKAkibAoGU291cmNlEgoKAmlkGAEgASgD",
            "EgwKBG5hbWUYAiABKAkSEAoIbGFuZ3VhZ2UYAyABKAkSEAoIaG9tZV91cmwY",
            "BCABKAkSEwoLbWlycm9yX3VybHMYBSADKAkSDwoHbWVzc2FnZRgHIAEoCSqA",
            "AQoOQ29udGVudFdhcm5pbmcSHwobQ09OVEVOVF9XQVJOSU5HX1VOU1BFQ0lG",
            "SUVEEAASGAoUQ09OVEVOVF9XQVJOSU5HX1NBRkUQARIZChVDT05URU5UX1dB",
            "Uk5JTkdfTUlYRUQQAhIYChRDT05URU5UX1dBUk5JTkdfTlNGVxADQh6qAhtO",
            "aXJhdGFuLk1vZGVscy5NYW5nYS5Qcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Niratan.Models.Manga.Protos.ContentWarning), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Niratan.Models.Manga.Protos.NetworkExtensionStore), global::Niratan.Models.Manga.Protos.NetworkExtensionStore.Parser, new[]{ "Name", "BadgeLabel", "SigningKey", "Contact", "ExtensionList", "ExtensionListUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niratan.Models.Manga.Protos.Contact), global::Niratan.Models.Manga.Protos.Contact.Parser, new[]{ "Website", "Discord" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niratan.Models.Manga.Protos.ExtensionList), global::Niratan.Models.Manga.Protos.ExtensionList.Parser, new[]{ "Extensions" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niratan.Models.Manga.Protos.Extension), global::Niratan.Models.Manga.Protos.Extension.Parser, new[]{ "Name", "PackageName", "Resources", "ExtensionLib", "VersionCode", "VersionName", "ContentWarning", "Sources" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niratan.Models.Manga.Protos.Resources), global::Niratan.Models.Manga.Protos.Resources.Parser, new[]{ "ApkUrl", "IconUrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Niratan.Models.Manga.Protos.Source), global::Niratan.Models.Manga.Protos.Source.Parser, new[]{ "Id", "Name", "Language", "HomeUrl", "MirrorUrls", "Message" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ContentWarning {
    [pbr::OriginalName("CONTENT_WARNING_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("CONTENT_WARNING_SAFE")] Safe = 1,
    [pbr::OriginalName("CONTENT_WARNING_MIXED")] Mixed = 2,
    [pbr::OriginalName("CONTENT_WARNING_NSFW")] Nsfw = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Top-level extension repository index.
  /// Mirrors Mihon's NetworkExtensionStore schema.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NetworkExtensionStore : pb::IMessage<NetworkExtensionStore>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NetworkExtensionStore> _parser = new pb::MessageParser<NetworkExtensionStore>(() => new NetworkExtensionStore());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NetworkExtensionStore> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niratan.Models.Manga.Protos.ExtensionRepoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetworkExtensionStore() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetworkExtensionStore(NetworkExtensionStore other) : this() {
      name_ = other.name_;
      badgeLabel_ = other.badgeLabel_;
      signingKey_ = other.signingKey_;
      contact_ = other.contact_ != null ? other.contact_.Clone() : null;
      extensionList_ = other.extensionList_ != null ? other.extensionList_.Clone() : null;
      extensionListUrl_ = other.extensionListUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetworkExtensionStore Clone() {
      return new NetworkExtensionStore(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "badge_label" field.</summary>
    public const int BadgeLabelFieldNumber = 2;
    private string badgeLabel_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BadgeLabel {
      get { return badgeLabel_; }
      set {
        badgeLabel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signing_key" field.</summary>
    public const int SigningKeyFieldNumber = 3;
    private string signingKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SigningKey {
      get { return signingKey_; }
      set {
        signingKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contact" field.</summary>
    public const int ContactFieldNumber = 4;
    private global::Niratan.Models.Manga.Protos.Contact contact_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niratan.Models.Manga.Protos.Contact Contact {
      get { return contact_; }
      set {
        contact_ = value;
      }
    }

    /// <summary>Field number for the "extension_list" field.</summary>
    public const int ExtensionListFieldNumber = 101;
    private global::Niratan.Models.Manga.Protos.ExtensionList extensionList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niratan.Models.Manga.Protos.ExtensionList ExtensionList {
      get { return extensionList_; }
      set {
        extensionList_ = value;
      }
    }

    /// <summary>Field number for the "extension_list_url" field.</summary>
    public const int ExtensionListUrlFieldNumber = 102;
    private string extensionListUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExtensionListUrl {
      get { return extensionListUrl_; }
      set {
        extensionListUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NetworkExtensionStore);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NetworkExtensionStore other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (BadgeLabel != other.BadgeLabel) return false;
      if (SigningKey != other.SigningKey) return false;
      if (!object.Equals(Contact, other.Contact)) return false;
      if (!object.Equals(ExtensionList, other.ExtensionList)) return false;
      if (ExtensionListUrl != other.ExtensionListUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (BadgeLabel.Length != 0) hash ^= BadgeLabel.GetHashCode();
      if (SigningKey.Length != 0) hash ^= SigningKey.GetHashCode();
      if (contact_ != null) hash ^= Contact.GetHashCode();
      if (extensionList_ != null) hash ^= ExtensionList.GetHashCode();
      if (ExtensionListUrl.Length != 0) hash ^= ExtensionListUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (BadgeLabel.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BadgeLabel);
      }
      if (SigningKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SigningKey);
      }
      if (contact_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Contact);
      }
      if (extensionList_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(ExtensionList);
      }
      if (ExtensionListUrl.Length != 0) {
        output.WriteRawTag(178, 6);
        output.WriteString(ExtensionListUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (BadgeLabel.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BadgeLabel);
      }
      if (SigningKey.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SigningKey);
      }
      if (contact_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Contact);
      }
      if (extensionList_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(ExtensionList);
      }
      if (ExtensionListUrl.Length != 0) {
        output.WriteRawTag(178, 6);
        output.WriteString(ExtensionListUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (BadgeLabel.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BadgeLabel);
      }
      if (SigningKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SigningKey);
      }
      if (contact_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Contact);
      }
      if (extensionList_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ExtensionList);
      }
      if (ExtensionListUrl.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ExtensionListUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NetworkExtensionStore other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.BadgeLabel.Length != 0) {
        BadgeLabel = other.BadgeLabel;
      }
      if (other.SigningKey.Length != 0) {
        SigningKey = other.SigningKey;
      }
      if (other.contact_ != null) {
        if (contact_ == null) {
          Contact = new global::Niratan.Models.Manga.Protos.Contact();
        }
        Contact.MergeFrom(other.Contact);
      }
      if (other.extensionList_ != null) {
        if (extensionList_ == null) {
          ExtensionList = new global::Niratan.Models.Manga.Protos.ExtensionList();
        }
        ExtensionList.MergeFrom(other.ExtensionList);
      }
      if (other.ExtensionListUrl.Length != 0) {
        ExtensionListUrl = other.ExtensionListUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            BadgeLabel = input.ReadString();
            break;
          }
          case 26: {
            SigningKey = input.ReadString();
            break;
          }
          case 34: {
            if (contact_ == null) {
              Contact = new global::Niratan.Models.Manga.Protos.Contact();
            }
            input.ReadMessage(Contact);
            break;
          }
          case 810: {
            if (extensionList_ == null) {
              ExtensionList = new global::Niratan.Models.Manga.Protos.ExtensionList();
            }
            input.ReadMessage(ExtensionList);
            break;
          }
          case 818: {
            ExtensionListUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            BadgeLabel = input.ReadString();
            break;
          }
          case 26: {
            SigningKey = input.ReadString();
            break;
          }
          case 34: {
            if (contact_ == null) {
              Contact = new global::Niratan.Models.Manga.Protos.Contact();
            }
            input.ReadMessage(Contact);
            break;
          }
          case 810: {
            if (extensionList_ == null) {
              ExtensionList = new global::Niratan.Models.Manga.Protos.ExtensionList();
            }
            input.ReadMessage(ExtensionList);
            break;
          }
          case 818: {
            ExtensionListUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Contact : pb::IMessage<Contact>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Contact> _parser = new pb::MessageParser<Contact>(() => new Contact());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Contact> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niratan.Models.Manga.Protos.ExtensionRepoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Contact() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Contact(Contact other) : this() {
      website_ = other.website_;
      discord_ = other.discord_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Contact Clone() {
      return new Contact(this);
    }

    /// <summary>Field number for the "website" field.</summary>
    public const int WebsiteFieldNumber = 1;
    private string website_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Website {
      get { return website_; }
      set {
        website_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "discord" field.</summary>
    public const int DiscordFieldNumber = 2;
    private string discord_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Discord {
      get { return discord_; }
      set {
        discord_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Contact);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Contact other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Website != other.Website) return false;
      if (Discord != other.Discord) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Website.Length != 0) hash ^= Website.GetHashCode();
      if (Discord.Length != 0) hash ^= Discord.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Website.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Website);
      }
      if (Discord.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Discord);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Website.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Website);
      }
      if (Discord.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Discord);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Website.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Website);
      }
      if (Discord.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Discord);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Contact other) {
      if (other == null) {
        return;
      }
      if (other.Website.Length != 0) {
        Website = other.Website;
      }
      if (other.Discord.Length != 0) {
        Discord = other.Discord;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Website = input.ReadString();
            break;
          }
          case 18: {
            Discord = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Website = input.ReadString();
            break;
          }
          case 18: {
            Discord = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ExtensionList : pb::IMessage<ExtensionList>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExtensionList> _parser = new pb::MessageParser<ExtensionList>(() => new ExtensionList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExtensionList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niratan.Models.Manga.Protos.ExtensionRepoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionList(ExtensionList other) : this() {
      extensions_ = other.extensions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtensionList Clone() {
      return new ExtensionList(this);
    }

    /// <summary>Field number for the "extensions" field.</summary>
    public const int ExtensionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Niratan.Models.Manga.Protos.Extension> _repeated_extensions_codec
        = pb::FieldCodec.ForMessage(10, global::Niratan.Models.Manga.Protos.Extension.Parser);
    private readonly pbc::RepeatedField<global::Niratan.Models.Manga.Protos.Extension> extensions_ = new pbc::RepeatedField<global::Niratan.Models.Manga.Protos.Extension>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Niratan.Models.Manga.Protos.Extension> Extensions {
      get { return extensions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExtensionList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExtensionList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!extensions_.Equals(other.extensions_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= extensions_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      extensions_.WriteTo(output, _repeated_extensions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      extensions_.WriteTo(ref output, _repeated_extensions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += extensions_.CalculateSize(_repeated_extensions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExtensionList other) {
      if (other == null) {
        return;
      }
      extensions_.Add(other.extensions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            extensions_.AddEntriesFrom(input, _repeated_extensions_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            extensions_.AddEntriesFrom(ref input, _repeated_extensions_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Extension : pb::IMessage<Extension>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Extension> _parser = new pb::MessageParser<Extension>(() => new Extension());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Extension> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niratan.Models.Manga.Protos.ExtensionRepoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Extension() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Extension(Extension other) : this() {
      name_ = other.name_;
      packageName_ = other.packageName_;
      resources_ = other.resources_ != null ? other.resources_.Clone() : null;
      extensionLib_ = other.extensionLib_;
      versionCode_ = other.versionCode_;
      versionName_ = other.versionName_;
      contentWarning_ = other.contentWarning_;
      sources_ = other.sources_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Extension Clone() {
      return new Extension(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "package_name" field.</summary>
    public const int PackageNameFieldNumber = 2;
    private string packageName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PackageName {
      get { return packageName_; }
      set {
        packageName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resources" field.</summary>
    public const int ResourcesFieldNumber = 3;
    private global::Niratan.Models.Manga.Protos.Resources resources_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niratan.Models.Manga.Protos.Resources Resources {
      get { return resources_; }
      set {
        resources_ = value;
      }
    }

    /// <summary>Field number for the "extension_lib" field.</summary>
    public const int ExtensionLibFieldNumber = 4;
    private string extensionLib_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExtensionLib {
      get { return extensionLib_; }
      set {
        extensionLib_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "version_code" field.</summary>
    public const int VersionCodeFieldNumber = 5;
    private long versionCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long VersionCode {
      get { return versionCode_; }
      set {
        versionCode_ = value;
      }
    }

    /// <summary>Field number for the "version_name" field.</summary>
    public const int VersionNameFieldNumber = 6;
    private string versionName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VersionName {
      get { return versionName_; }
      set {
        versionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content_warning" field.</summary>
    public const int ContentWarningFieldNumber = 7;
    private global::Niratan.Models.Manga.Protos.ContentWarning contentWarning_ = global::Niratan.Models.Manga.Protos.ContentWarning.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Niratan.Models.Manga.Protos.ContentWarning ContentWarning {
      get { return contentWarning_; }
      set {
        contentWarning_ = value;
      }
    }

    /// <summary>Field number for the "sources" field.</summary>
    public const int SourcesFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Niratan.Models.Manga.Protos.Source> _repeated_sources_codec
        = pb::FieldCodec.ForMessage(66, global::Niratan.Models.Manga.Protos.Source.Parser);
    private readonly pbc::RepeatedField<global::Niratan.Models.Manga.Protos.Source> sources_ = new pbc::RepeatedField<global::Niratan.Models.Manga.Protos.Source>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Niratan.Models.Manga.Protos.Source> Sources {
      get { return sources_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Extension);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Extension other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (PackageName != other.PackageName) return false;
      if (!object.Equals(Resources, other.Resources)) return false;
      if (ExtensionLib != other.ExtensionLib) return false;
      if (VersionCode != other.VersionCode) return false;
      if (VersionName != other.VersionName) return false;
      if (ContentWarning != other.ContentWarning) return false;
      if(!sources_.Equals(other.sources_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (PackageName.Length != 0) hash ^= PackageName.GetHashCode();
      if (resources_ != null) hash ^= Resources.GetHashCode();
      if (ExtensionLib.Length != 0) hash ^= ExtensionLib.GetHashCode();
      if (VersionCode != 0L) hash ^= VersionCode.GetHashCode();
      if (VersionName.Length != 0) hash ^= VersionName.GetHashCode();
      if (ContentWarning != global::Niratan.Models.Manga.Protos.ContentWarning.Unspecified) hash ^= ContentWarning.GetHashCode();
      hash ^= sources_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (PackageName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PackageName);
      }
      if (resources_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Resources);
      }
      if (ExtensionLib.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExtensionLib);
      }
      if (VersionCode != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(VersionCode);
      }
      if (VersionName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(VersionName);
      }
      if (ContentWarning != global::Niratan.Models.Manga.Protos.ContentWarning.Unspecified) {
        output.WriteRawTag(56);
        output.WriteEnum((int) ContentWarning);
      }
      sources_.WriteTo(output, _repeated_sources_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (PackageName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PackageName);
      }
      if (resources_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Resources);
      }
      if (ExtensionLib.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExtensionLib);
      }
      if (VersionCode != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(VersionCode);
      }
      if (VersionName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(VersionName);
      }
      if (ContentWarning != global::Niratan.Models.Manga.Protos.ContentWarning.Unspecified) {
        output.WriteRawTag(56);
        output.WriteEnum((int) ContentWarning);
      }
      sources_.WriteTo(ref output, _repeated_sources_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (PackageName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PackageName);
      }
      if (resources_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resources);
      }
      if (ExtensionLib.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExtensionLib);
      }
      if (VersionCode != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(VersionCode);
      }
      if (VersionName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VersionName);
      }
      if (ContentWarning != global::Niratan.Models.Manga.Protos.ContentWarning.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ContentWarning);
      }
      size += sources_.CalculateSize(_repeated_sources_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Extension other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.PackageName.Length != 0) {
        PackageName = other.PackageName;
      }
      if (other.resources_ != null) {
        if (resources_ == null) {
          Resources = new global::Niratan.Models.Manga.Protos.Resources();
        }
        Resources.MergeFrom(other.Resources);
      }
      if (other.ExtensionLib.Length != 0) {
        ExtensionLib = other.ExtensionLib;
      }
      if (other.VersionCode != 0L) {
        VersionCode = other.VersionCode;
      }
      if (other.VersionName.Length != 0) {
        VersionName = other.VersionName;
      }
      if (other.ContentWarning != global::Niratan.Models.Manga.Protos.ContentWarning.Unspecified) {
        ContentWarning = other.ContentWarning;
      }
      sources_.Add(other.sources_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            PackageName = input.ReadString();
            break;
          }
          case 26: {
            if (resources_ == null) {
              Resources = new global::Niratan.Models.Manga.Protos.Resources();
            }
            input.ReadMessage(Resources);
            break;
          }
          case 34: {
            ExtensionLib = input.ReadString();
            break;
          }
          case 40: {
            VersionCode = input.ReadInt64();
            break;
          }
          case 50: {
            VersionName = input.ReadString();
            break;
          }
          case 56: {
            ContentWarning = (global::Niratan.Models.Manga.Protos.ContentWarning) input.ReadEnum();
            break;
          }
          case 66: {
            sources_.AddEntriesFrom(input, _repeated_sources_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            PackageName = input.ReadString();
            break;
          }
          case 26: {
            if (resources_ == null) {
              Resources = new global::Niratan.Models.Manga.Protos.Resources();
            }
            input.ReadMessage(Resources);
            break;
          }
          case 34: {
            ExtensionLib = input.ReadString();
            break;
          }
          case 40: {
            VersionCode = input.ReadInt64();
            break;
          }
          case 50: {
            VersionName = input.ReadString();
            break;
          }
          case 56: {
            ContentWarning = (global::Niratan.Models.Manga.Protos.ContentWarning) input.ReadEnum();
            break;
          }
          case 66: {
            sources_.AddEntriesFrom(ref input, _repeated_sources_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Resources : pb::IMessage<Resources>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Resources> _parser = new pb::MessageParser<Resources>(() => new Resources());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Resources> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niratan.Models.Manga.Protos.ExtensionRepoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Resources() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Resources(Resources other) : this() {
      apkUrl_ = other.apkUrl_;
      iconUrl_ = other.iconUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Resources Clone() {
      return new Resources(this);
    }

    /// <summary>Field number for the "apk_url" field.</summary>
    public const int ApkUrlFieldNumber = 1;
    private string apkUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ApkUrl {
      get { return apkUrl_; }
      set {
        apkUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "icon_url" field.</summary>
    public const int IconUrlFieldNumber = 2;
    private string iconUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IconUrl {
      get { return iconUrl_; }
      set {
        iconUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Resources);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Resources other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ApkUrl != other.ApkUrl) return false;
      if (IconUrl != other.IconUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ApkUrl.Length != 0) hash ^= ApkUrl.GetHashCode();
      if (IconUrl.Length != 0) hash ^= IconUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ApkUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ApkUrl);
      }
      if (IconUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IconUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ApkUrl.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ApkUrl);
      }
      if (IconUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IconUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ApkUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApkUrl);
      }
      if (IconUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IconUrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Resources other) {
      if (other == null) {
        return;
      }
      if (other.ApkUrl.Length != 0) {
        ApkUrl = other.ApkUrl;
      }
      if (other.IconUrl.Length != 0) {
        IconUrl = other.IconUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ApkUrl = input.ReadString();
            break;
          }
          case 18: {
            IconUrl = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ApkUrl = input.ReadString();
            break;
          }
          case 18: {
            IconUrl = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Source : pb::IMessage<Source>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Source> _parser = new pb::MessageParser<Source>(() => new Source());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Source> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Niratan.Models.Manga.Protos.ExtensionRepoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Source() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Source(Source other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      language_ = other.language_;
      homeUrl_ = other.homeUrl_;
      mirrorUrls_ = other.mirrorUrls_.Clone();
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Source Clone() {
      return new Source(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "language" field.</summary>
    public const int LanguageFieldNumber = 3;
    private string language_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Language {
      get { return language_; }
      set {
        language_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "home_url" field.</summary>
    public const int HomeUrlFieldNumber = 4;
    private string homeUrl_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HomeUrl {
      get { return homeUrl_; }
      set {
        homeUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mirror_urls" field.</summary>
    public const int MirrorUrlsFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_mirrorUrls_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> mirrorUrls_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> MirrorUrls {
      get { return mirrorUrls_; }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 7;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Source);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Source other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Language != other.Language) return false;
      if (HomeUrl != other.HomeUrl) return false;
      if(!mirrorUrls_.Equals(other.mirrorUrls_)) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Language.Length != 0) hash ^= Language.GetHashCode();
      if (HomeUrl.Length != 0) hash ^= HomeUrl.GetHashCode();
      hash ^= mirrorUrls_.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Language.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Language);
      }
      if (HomeUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(HomeUrl);
      }
      mirrorUrls_.WriteTo(output, _repeated_mirrorUrls_codec);
      if (Message.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Language.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Language);
      }
      if (HomeUrl.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(HomeUrl);
      }
      mirrorUrls_.WriteTo(ref output, _repeated_mirrorUrls_codec);
      if (Message.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Language.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Language);
      }
      if (HomeUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HomeUrl);
      }
      size += mirrorUrls_.CalculateSize(_repeated_mirrorUrls_codec);
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Source other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Language.Length != 0) {
        Language = other.Language;
      }
      if (other.HomeUrl.Length != 0) {
        HomeUrl = other.HomeUrl;
      }
      mirrorUrls_.Add(other.mirrorUrls_);
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Language = input.ReadString();
            break;
          }
          case 34: {
            HomeUrl = input.ReadString();
            break;
          }
          case 42: {
            mirrorUrls_.AddEntriesFrom(input, _repeated_mirrorUrls_codec);
            break;
          }
          case 58: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Language = input.ReadString();
            break;
          }
          case 34: {
            HomeUrl = input.ReadString();
            break;
          }
          case 42: {
            mirrorUrls_.AddEntriesFrom(ref input, _repeated_mirrorUrls_codec);
            break;
          }
          case 58: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
