using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Niratan.Models;
using YoutubeExplode;
using YoutubeExplode.Exceptions;
using YoutubeExplode.Videos.ClosedCaptions;
using YoutubeExplode.Videos.Streams;

namespace Niratan.Services.Video;

internal sealed record YouTubeRemoteMetadata(
    string Title,
    string? ThumbnailUrl,
    TimeSpan? Duration);

internal interface IYoutubeExplodeClientAdapter : IDisposable
{
    Task<YouTubeRemoteMetadata> GetMetadataAsync(string videoId, CancellationToken ct);
    Task<IReadOnlyList<RemoteVideoStream>> GetStreamsAsync(string videoId, CancellationToken ct);
    Task<IReadOnlyList<RemoteVideoSubtitleOption>> GetSubtitlesAsync(string videoId, CancellationToken ct);
    Task DownloadSubtitleAsync(RemoteVideoSubtitleOption option, string outputPath, CancellationToken ct);
}

internal sealed class YoutubeExplodeClientAdapter : IYoutubeExplodeClientAdapter
{
    private static readonly IReadOnlyDictionary<string, string> PlaybackHeaders =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Referer"] = "https://www.youtube.com/",
            ["Origin"] = "https://www.youtube.com",
            ["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                             + "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
        };

    private readonly YoutubeClient _client = new();

    public async Task<YouTubeRemoteMetadata> GetMetadataAsync(string videoId, CancellationToken ct)
    {
        var metadata = await ExecuteAsync(() => _client.Videos.GetAsync(videoId, ct).AsTask());
        var thumbnail = metadata.Thumbnails
            .OrderByDescending(item => item.Resolution.Width * item.Resolution.Height)
            .FirstOrDefault()?.Url;
        return new YouTubeRemoteMetadata(metadata.Title, thumbnail, metadata.Duration);
    }

    public async Task<IReadOnlyList<RemoteVideoStream>> GetStreamsAsync(string videoId, CancellationToken ct)
    {
        var manifest = await ExecuteAsync(() => _client.Videos.Streams.GetManifestAsync(videoId, ct).AsTask());
        return manifest.Streams.Select(ToRemoteStream).ToList();
    }

    public async Task<IReadOnlyList<RemoteVideoSubtitleOption>> GetSubtitlesAsync(
        string videoId,
        CancellationToken ct)
    {
        var manifest = await ExecuteAsync(() => _client.Videos.ClosedCaptions.GetManifestAsync(videoId, ct).AsTask());
        return manifest.Tracks.Select((track, index) => new RemoteVideoSubtitleOption(
            $"{track.Language.Code}:{index}",
            track.Language.Code,
            track.Language.Name,
            track.Url,
            track.IsAutoGenerated)).ToList();
    }

    public async Task DownloadSubtitleAsync(
        RemoteVideoSubtitleOption option,
        string outputPath,
        CancellationToken ct)
    {
        var track = new ClosedCaptionTrackInfo(
            option.SourceUrl,
            new Language(option.Language, option.Name),
            option.IsAutomatic);
        await ExecuteAsync(async () =>
        {
            await _client.Videos.ClosedCaptions.DownloadAsync(track, outputPath, cancellationToken: ct);
            return true;
        });
    }

    public void Dispose() => _client.Dispose();

    private static RemoteVideoStream ToRemoteStream(IStreamInfo stream)
    {
        var video = stream as IVideoStreamInfo;
        var audio = stream as IAudioStreamInfo;
        return new RemoteVideoStream(
            stream.Url,
            ParseQueryValue(stream.Url, "itag") ?? stream.Url.GetHashCode(StringComparison.Ordinal).ToString("x"),
            video?.VideoQuality.MaxHeight,
            video != null,
            audio != null,
            stream.Container.Name,
            video?.VideoCodec,
            audio?.AudioCodec,
            stream.Bitrate.BitsPerSecond,
            PlaybackHeaders);
    }

    private static async Task<T> ExecuteAsync<T>(Func<Task<T>> action)
    {
        try
        {
            return await action();
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (RequestLimitExceededException ex)
        {
            throw new RemoteVideoResolverException(RemoteVideoResolverError.RateLimited, ex);
        }
        catch (VideoRequiresPurchaseException ex)
        {
            throw new RemoteVideoResolverException(RemoteVideoResolverError.SignInRequired, ex);
        }
        catch (VideoUnavailableException ex)
        {
            throw new RemoteVideoResolverException(RemoteVideoResolverError.ContentUnavailable, ex);
        }
        catch (VideoUnplayableException ex)
        {
            throw new RemoteVideoResolverException(MapUnplayable(ex.Message), ex);
        }
        catch (HttpRequestException ex)
        {
            throw new RemoteVideoResolverException(RemoteVideoResolverError.ResolutionFailed, ex);
        }
    }

    private static RemoteVideoResolverError MapUnplayable(string message)
    {
        if (message.Contains("region", StringComparison.OrdinalIgnoreCase)
            || message.Contains("country", StringComparison.OrdinalIgnoreCase))
            return RemoteVideoResolverError.RegionRestricted;
        if (message.Contains("age", StringComparison.OrdinalIgnoreCase)
            || message.Contains("sign in", StringComparison.OrdinalIgnoreCase)
            || message.Contains("members", StringComparison.OrdinalIgnoreCase))
            return RemoteVideoResolverError.SignInRequired;
        return RemoteVideoResolverError.ContentUnavailable;
    }

    private static string? ParseQueryValue(string url, string key)
    {
        if (!Uri.TryCreate(url, UriKind.Absolute, out var uri))
            return null;

        foreach (var item in uri.Query.TrimStart('?').Split('&', StringSplitOptions.RemoveEmptyEntries))
        {
            var separator = item.IndexOf('=');
            var name = Uri.UnescapeDataString(separator < 0 ? item : item[..separator]);
            if (name.Equals(key, StringComparison.Ordinal))
                return Uri.UnescapeDataString(separator < 0 ? string.Empty : item[(separator + 1)..]);
        }

        return null;
    }
}
